name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-aarch64-darwin:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Build
      run: cargo build --release
    
    - name: Upload binary to release
      uses: softprops/action-gh-release@v2
      with:
        files: ./target/release/journo